---

- name: "SourceCodePro: download and install"
  get_url: url={{item}} mode=0440 dest="{{ ansible_env.HOME}}/.fonts"
  with_items:
    - "https://github.com/adobe-fonts/source-code-pro/releases/download/variable-fonts/SourceCodeVariable-Italic.otf"
    - "https://github.com/adobe-fonts/source-code-pro/releases/download/variable-fonts/SourceCodeVariable-Roman.otf"

- name: "SourceCodePro: rebuild font cache"
  shell: fc-cache -f -v
