---

- name: "Fonts: ensure ~/.fonts exists"
  file:
    path: "{{ ansible_env.HOME }}/.fonts"
    state: directory
    mode: 0755

- name: "Fonts: install fonts"
  copy: src={{item}} dest="{{ ansible_env.HOME }}/.fonts"
  with_items:
    - SourceCodePro-Black.otf
    - SourceCodePro-BlackIt.otf
    - SourceCodePro-Bold.otf
    - SourceCodePro-BoldIt.otf
    - SourceCodePro-ExtraLight.otf
    - SourceCodePro-ExtraLightIt.otf
    - SourceCodePro-It.otf
    - SourceCodePro-Light.otf
    - SourceCodePro-LightIt.otf
    - SourceCodePro-Medium.otf
    - SourceCodePro-MediumIt.otf
    - SourceCodePro-Regular.otf
    - SourceCodePro-Semibold.otf
    - SourceCodePro-SemiboldIt.otf

- name: "Fonts: rebuild font cache"
  shell: fc-cache -f -v
