---

- name: "Vim: Install package"
  become: yes
  apt:
    name: vim-nox
    state: present
    update_cache: yes

- name: "Vim: clone config"
  git:
    repo: "https://github.com/elliotf/vim-config.git"
    dest: "{{ ansible_env.HOME }}/.vim"

- name: "Vim: symlink .vimrc"
  file:
    src: "{{ ansible_env.HOME }}/.vim/vimrc"
    dest: "{{ ansible_env.HOME }}/.vimrc"
    state: link

- name: "Vim: use bash's vim command line mode"
  lineinfile: dest=~/.bashrc line="set -o vi" create=yes

- name: "Vim: make vim the default editor"
  lineinfile: dest=~/.profile line="export EDITOR=vim" create=yes
